### ISSUE TITLE
Integrate money system

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/Essential_Freeroam#1]
## Completed
- [X] Load the players money when signing in.

**Comment by BawlzOnChin** [comment]
Integrate money into jobs : Trucker Job, Taxi Job, etc... 
Integrate money into purchases: VehShop, Stores, Businesses, Los Santos Customs

**Comment by BawlzOnChin** [comment]
/givemoney command so players can give each other money when selling a car or doing a drug deal etc..
