### ISSUE TITLE
Server won't start after adding es_freeroam

### ISSUE THREAD

**Issue by 320thSTSMilSim** [FiveM-Scripts/Essential_Freeroam#29]
Hello,
When I try to add the es_freeroam resource into the [essential] folder and add it to my citmp-server.yml, it seems to stop my server from loading. I do have essentialmode, but it won't show up on the server list and it makes 3 attempts to connect for it rejects my connection. Once I removed freeroam from the resources, the sever came right up. Is there something else that needs to go along with this to make it work? Are there other resources it's not compatible with? Here are my resources.
![screen1](https://cloud.githubusercontent.com/assets/16441364/24335118/1ca2a8b2-122c-11e7-9d8f-49c9924381b9.jpg)
![screen2](https://cloud.githubusercontent.com/assets/16441364/24335117/1ca25d9e-122c-11e7-9bad-59e012375c88.jpg)
![screen3](https://cloud.githubusercontent.com/assets/16441364/24335119/1ca3295e-122c-11e7-94d6-032a91b24661.jpg)

**Comment by ghermans** [comment]
Can you try something like this?

```
AutoStartResources:
    - chat
    - spawnmanager
    - essentialmode
    - es_freeroam
    - es_admin
    - fivem-map-skater
    - rconlog
    - hardcap
    - baseevents
    - rconlog
    - hardcap # prevents too many players from joining
```

**Comment by 320thSTSMilSim** [comment]
Can you please clarify? You say to place it in the [essential] folder, but on the post above you say to try what you posted which shows es_freeroam not in [essential]. Which way should I do it? Your help is greatly appreciated! :)

**Comment by ghermans** [comment]
I mean like this...   

![dsrzerzknipsel](https://cloud.githubusercontent.com/assets/1594411/24341051/36721a26-12b7-11e7-8d87-7d7033404a68.PNG)

and then in your  citmp-server.yml:

```
AutoStartResources:
    - chat
    - spawnmanager
    **- essentialmode
    - es_freeroam**
    - es_admin
    - fivem-map-skater
    - rconlog
    - hardcap
    - baseevents
    - rconlog
    - hardcap # prevents too many players from joining
```

**Comment by 320thSTSMilSim** [comment]
ok i tried it, but server is still not coming up. I did exactly what you have above. Still nothing. There was an update on 5M, but I don't think it was anything that would conflict. Not sure. Here are my screenshots showing exactly they way you have it. The 2nd screenshot is my cache. Those are the only files being cached.
![cache](https://cloud.githubusercontent.com/assets/16441364/24341362/fcacdb76-126d-11e7-8bca-537def08b9a4.jpg)
![screen4](https://cloud.githubusercontent.com/assets/16441364/24341361/fcac4e22-126d-11e7-99f3-a7e41f541a1a.jpg)
